### PR TITLE
Backport 138

### PR DESCRIPTION
**Pull request by mrkn**
For #139

### CODE REVIEW

**Comment by mrkn** [comment]
I don't know why `bundle install` is failed only on Ruby 2.6 in Appveyor...

**Comment by kou** [comment]
You need to use "Visual Studio 2017" worker image https://www.appveyor.com/docs/build-environment/#build-worker-images for Ruby 2.6.

You can change worker image via https://ci.appveyor.com/project/ruby/bigdecimal/settings/environment or adding `image: Visual Studio 2017` to `appveyor.yml: https://www.appveyor.com/docs/build-environment/#choosing-image-for-your-builds

**Comment by mrkn** [comment]
@kou thank you very much!  I'll try it.

**Comment by mrkn** [comment]
AppVeyor shows the wrong table https://www.appveyor.com/docs/windows-images-software/#ruby

**Comment by mrkn** [comment]
@kou thank you very much!

**Comment by kou** [comment]
No problem. :-)

**Pull request merged**
