### PR TITLE
Let BigDecimal#quo accept precision

### PR DESCRIPTION
**Pull request by mrkn**
Fix GH-214.

### CODE REVIEW

**Comment by mrkn** [comment]
TODO:
- [ ] Support larger precision than the precision of the default result.

**Review by olleolleolle — APPROVED** [review]
To me, a casual reader, it looks good.

**Comment by olleolleolle** [comment]
@mrkn I read the carefully-worded documentation! :-)

**Comment by mrkn** [comment]
OK, I see.  Thank you for checking the documentation part.  But it needs to be modified after I will implement the longer precision support.  Could you please check the update later.


By the way, the approval check only for the documentation part is noisy to me because the main topic of this PR is updating the logic of `BigDecimal#quo`.  Could you please stop checking approval only for the documentation part to non-documentation PRs?  Instead, it's easier to understand your intention that telling your opinion in comments at the documentation lines.

**Comment by mrkn** [comment]
@olleolleolle Could you check the documentation update?

**Comment by mrkn** [comment]
@olleolleolle I'll merge this. Please create a new PR to fix the documentation if you find some mistakes.

**Comment by olleolleolle** [comment]
(Reads perfectly, thanks!)

**Pull request merged**
