### PR TITLE
Correctly computing loop iterations in `BigDecimal#sqrt`

### PR DESCRIPTION
**Pull request by z2-2z**

### CODE REVIEW

**Comment by mrkn** [comment]
@z2-2z Thank you very much!

**Comment by hsbt** [comment]
This change break i686 environment https://github.com/ruby/ruby/actions/runs/7321152433/job/19941861006

**Comment by mrkn** [comment]
@hsbt Did you compile the ruby you used with `-msse2 -mfpmath=sse`?

**Comment by mrkn** [comment]
I'm interested in what is the cause of that failure, but I have no desire to continue full support for the i686 environment.

**Pull request merged**
